---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: mldp
networking:
  apiServerPort: 6443
nodes:
  - role: control-plane
    image: kindest/node:v1.28.6
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
  - role: worker
    image: kindest/node:v1.28.6
  - role: worker
    image: kindest/node:v1.28.6
